global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'team-api'

receivers:
  - name: 'team-api'
    slack_configs:
      - channel: '#alerts'
        send_resolved: true 