groups:
  - name: lang-portal
    rules:
      - record: api:request_duration_seconds:p95
        expr: histogram_quantile(0.95, sum(rate(handler_request_duration_bucket[5m])) by (le, handler))

      - record: api:error_rate
        expr: sum(rate(handler_error_count[5m])) / sum(rate(handler_request_count[5m]))

      - alert: HighErrorRate
        expr: api:error_rate > 0.01
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: Error rate is {{ $value | humanizePercentage }} (> 1%)

      - alert: HighLatency
        expr: api:request_duration_seconds:p95 > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          description: 95th percentile latency is {{ $value | humanizeDuration }}

      - alert: HighDBConnections
        expr: sum(db_connections_in_use) / sum(db_connections_max) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High database connection usage
          description: Database connection pool is {{ $value | humanizePercentage }} full 