server:
  global:
    scrape_interval: 15s
    evaluation_interval: 15s

  alerting:
    alertmanagers:
      - static_configs:
          - targets: ["alertmanager:9093"]

  rules:
    - name: lang-portal
      rules_dir: /etc/prometheus/rules

  persistence:
    enabled: true
    size: 50Gi

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'category']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack'
    receivers:
      - name: 'slack'
        slack_configs:
          - channel: '#alerts'
            send_resolved: true 